# Generated by Django 5.0.7 on 2024-08-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign_cohort',
            name='cohort_id',
        ),
        migrations.RemoveField(
            model_name='assign_cohort',
            name='user_id',
        ),
        migrations.AddField(
            model_name='result',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Cohort',
        ),
        migrations.DeleteModel(
            name='Assign_Cohort',
        ),
    ]
