# Generated by Django 5.0.6 on 2024-08-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='cohort_id',
        ),
    ]
