# Generated by Django 5.0.6 on 2024-08-08 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_lesson_cohort_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('statement', models.TextField(max_length=255)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Question_fillblank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.question')),
            ],
        ),
        migrations.CreateModel(
            name='Question_MCQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.question')),
            ],
        ),
        migrations.CreateModel(
            name='Question_truefalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.question')),
            ],
        ),
    ]
